### ISSUE TITLE
Way to set resolution to whatever the normal would be when downloading a book from archive.org

### ISSUE THREAD

**Issue by fivestones** [MiniGlome/Archive.org-Downloader#24]
When I tried downloading a book with various resolution levels, and then also just borrowed the book and downloaded it to adobe digital editions, the version that downloaded is about 50 MB, and downloading with -r 3 is 151 MB and with -r 4 is 48 MB. The 48 MB pdf is quite a bit smaller when fully zoomed in compared to the adobe digital editions version fully zoomed in.

I guess it would be great to be able to download a version that is the same size as what you get when downloading to adobe digital editions--both size in MB and size in inches when fully zoomed in.

Is this possible?

Thanks!

**Comment by darnn** [comment]
I speak only as a fellow user, but:
The Digital Editions PDF is smaller in filesize and looks different because the images in it have been processed. Actually processing the images is beyond the scope of this project, presumably, but if you want to try it yourself, I recommend [ScanTailor Advanced](https://github.com/vigri/scantailor-advanced#scantailor-advanced). I'm also not sure you could just download the Digital Edition PDFs through this program either, because you'd need to remove their DRM to be able to use them outside of Digital Editions, but to do that you'd have to open them in Digital Editions anyway, so it would be a moot point.
Bear in mind that you're better off having the raw images than the Digital Editions PDFs, because sometimes the scan is blurry, and in those cases the PDFs are much less readable than the images.

**Comment by fivestones** [comment]
Thanks for the info, that's helpful!
