### ISSUE TITLE
download OCR

### ISSUE THREAD

**Issue by Montoro30** [MiniGlome/Archive.org-Downloader#82]
Sorry to ask, but I would like to know if it's possible to download books with OCR (if available) directly from archive.org or just the images.
Thank you.

**Comment by Montoro30** [comment]
Thank you very much.
I asked because I found an old book taken from there on another site, and what caught my attention was the number of pages (over 1000) with a considerably small size and a simply perfect OCR. (I use Adobe, but I can't get the quality seen in this book).
And since it is a very laborious process and requires processing, the probability that someone had already downloaded it with OCR was high, hence my curiosity.

**Comment by darnn** [comment]
If a book can be borrowed for 14 days, you can download an OCRed PDF of it. Otherwise you'll have to do it yourself. It's not really that laborious, though: Just run them through ScanTailor Advanced without changing any page sizes (that is, "content box" should be set to "disabled" in content, and margins set to 0,0,0,0), and then OCR the result with whatever you use for that (I use FineReader since it's the best at handing Hebrew at the moment).
I can give you more detailed instructions if you want (let me know what your email address is, if so). Really, once you have the image files of the pages, it only takes a few minutes of work if you're not interested in tweaking anything.

**Comment by Montoro30** [comment]
Ahhh no, unfortunately they aren't books that can be borrowed for a long period... I greatly appreciate your availability, but it won't be necessary. Well, it really not laborious, however it does require some processing which, for a PC like mine, is quite cumbersome.
Regarding the software, I've already tested almost all the main ones on the market: FineReader, Adobe DC, Nitro, Abbyy, etc and weighing all the pros and cons, for my needs, Adobe fared better, although technically FineReader is higher.
Thank you.
