### ISSUE TITLE
guide to download

### ISSUE THREAD

**Issue by Git-Vasanth** [MiniGlome/Archive.org-Downloader#94]
hi. i used to download the pics and glad that i found this option.i did run the git commmands and trid to run the cmd which download the books. i got error in cmd , i have attached the picture. i do have pthon 3.12 but dont know whats wrong. please help me.i have downloaded in git. guide me next steps.

Thanks
![Screenshot (5009)](https://github.com/MiniGlome/Archive.org-Downloader/assets/59464869/701ec68d-7544-4c06-8d9c-f4bcc96a5e66)
![Screenshot (5010)](https://github.com/MiniGlome/Archive.org-Downloader/assets/59464869/0dac1339-2372-4cf7-a4fe-9353b3e01d39)

**Comment by darnn** [comment]
The developer (or someone else more knowledgeable than myself) can probably give you an answer that isn't a guess, but I'd try two things:
1. Change "python3" to "python3.exe" (or python.exe, that's what it is for me).
2. Get rid of the -dir parameter, or at least use single backslashes in the path rather than double.

Personally I'd also recommend that you use -j and compile the page images into a PDF yourself, since that way you have more control over how that happens, but that's just me. Also, back in the day I had problems with the PDF portion of the script and commented out the part that imports it, I think.

**Comment by Git-Vasanth** [comment]
i have tried , it says this.
![Screenshot (5011)](https://github.com/MiniGlome/Archive.org-Downloader/assets/59464869/0e4a6845-3778-496a-9da6-cfd74f87f34f)

**Comment by Git-Vasanth** [comment]
dude this is awesome. its working. i dont know your name but thank you

**Comment by darnn** [comment]
It's all good! Really, the developer is the one who deserves the thanks, I don't know the first thing about actually coding in Python, and this script has helped me immensely too.
