### ISSUE TITLE
Invalid credentials

### ISSUE THREAD

**Issue by arhipov-rp** [MiniGlome/Archive.org-Downloader#96]
Until recently, everything worked fine, and now I get an error:
![image](https://github.com/MiniGlome/Archive.org-Downloader/assets/39758896/cda88957-4506-4287-83c7-0d0119550b2e)

There are no problems with the same credentials on the site.

Windows 10, python 3.12.0

**Comment by darnn** [comment]
And it has nothing to do with the fact that the book is currently already borrowed?

**Comment by arhipov-rp** [comment]
> And it has nothing to do with the fact that the book is currently already borrowed?

No, I tried both (borrowed and not borrowed).

**Comment by darnn** [comment]
In that case, try different credentials and/or a VPN, since you may be getting throttled. Other than that, you'd have to wait and see if the developer has any suggestions.

**Comment by MiniGlome** [comment]
The problem seems to be coming from your credentials or connection.
Try creating a new account (temporary emails work well --> https://temp-mail.org/) and avoid using spaces in your password or use quotes in the command line.
Or you can try with this account I just created: `-e wigir24540@bixolabs.com -p aaaaaa`
